@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <span>Reports</span>
                    <a href="{{ route('reports.create') }}" class="btn btn-primary btn-sm">Generate New Report</a>
                </div>

                <div class="card-body">
                    @if (session('success'))
                    <div class="alert alert-success" role="alert">
                        {{ session('success') }}
                    </div>
                    @endif

                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Type</th>
                                    <th>Generated By</th>
                                    <th>Report Date</th>
                                    <th>Period</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($reports as $report)
                                <tr>
                                    <td>{{ $report->title }}</td>
                                    <td>{{ ucfirst($report->report_type) }}</td>
                                    <td>{{ $report->user ? $report->user->name : 'Unknown' }}</td>
                                    <td>{{ $report->report_date->format('Y-m-d') }}</td>
                                    <td>{{ $report->start_date->format('Y-m-d') }} to {{ $report->end_date->format('Y-m-d') }}</td>
                                    <td>
                                        <a href="{{ route('reports.show', $report->id) }}" class="btn btn-info btn-sm">View</a>
                                        <form action="{{ route('reports.destroy', $report->id) }}" method="POST" class="d-inline">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete this report?')">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="6" class="text-center">No reports found.</td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection