@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <span>{{ $report->title }}</span>
                    <div>
                        <a href="{{ route('reports.index') }}" class="btn btn-sm btn-secondary">Back to Reports</a>
                        <form action="{{ route('reports.destroy', $report->id) }}" method="POST" class="d-inline">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-sm btn-danger"
                                onclick="return confirm('Are you sure you want to delete this report?')">Delete</button>
                        </form>
                    </div>
                </div>

                <div class="card-body">
                    <div class="row mb-4">
                        <div class="col-md-6">
                            <h6>Report Information</h6>
                            <table class="table table-sm">
                                <tr>
                                    <th width="200">Report Type</th>
                                    <td>{{ ucfirst($report->report_type) }}</td>
                                </tr>
                                <tr>
                                    <th>Generated By</th>
                                    <td>{{ $report->user ? $report->user->name : 'Unknown' }}</td>
                                </tr>
                                <tr>
                                    <th>Date Range</th>
                                    <td>{{ $report->start_date->format('M d, Y') }} - {{ $report->end_date->format('M d, Y') }}</td>
                                </tr>
                                <tr>
                                    <th>Report Date</th>
                                    <td>{{ $report->report_date->format('M d, Y H:i') }}</td>
                                </tr>
                                @if($report->parameters)
                                @foreach($report->parameters as $key => $value)
                                <tr>
                                    <th>{{ ucfirst(str_replace('_', ' ', $key)) }}</th>
                                    <td>
                                        @if($key == 'supplier_id' && !empty($value))
                                        {{ \App\Models\Supplier::find($value)->name ?? 'Unknown' }}
                                        @elseif($key == 'department_id' && !empty($value))
                                        {{ \App\Models\Department::find($value)->name ?? 'Unknown' }}
                                        @else
                                        {{ $value }}
                                        @endif
                                    </td>
                                </tr>
                                @endforeach
                                @endif
                            </table>
                        </div>
                        <div class="col-md-6">
                            <h6>Summary</h6>
                            <table class="table table-sm">
                                @if($report->report_type == 'inventory')
                                <tr>
                                    <th width="200">Total Products</th>
                                    <td>{{ $report->data['total_products'] }}</td>
                                </tr>
                                <tr>
                                    <th>Total Value</th>
                                    <td>${{ number_format($report->data['total_value'], 2) }}</td>
                                </tr>
                                <tr>
                                    <th>Low Stock Items</th>
                                    <td>{{ $report->data['low_stock_items'] }}</td>
                                </tr>
                                @elseif($report->report_type == 'purchase_order')
                                <tr>
                                    <th width="200">Total Orders</th>
                                    <td>{{ $report->data['total_orders'] }}</td>
                                </tr>
                                <tr>
                                    <th>Total Amount</th>
                                    <td>${{ number_format($report->data['total_amount'], 2) }}</td>
                                </tr>
                                @foreach($report->data['by_status'] as $status => $count)
                                <tr>
                                    <th>{{ ucfirst($status) }}</th>
                                    <td>{{ $count }}</td>
                                </tr>
                                @endforeach
                                @elseif($report->report_type == 'issue')
                                <tr>
                                    <th width="200">Total Issues</th>
                                    <td>{{ $report->data['total_issues'] }}</td>
                                </tr>
                                <tr>
                                    <th>Total Items Issued</th>
                                    <td>{{ $report->data['total_items_issued'] }}</td>
                                </tr>
                                @elseif($report->report_type == 'supplier')
                                <tr>
                                    <th width="200">Total Suppliers</th>
                                    <td>{{ $report->data['total_suppliers'] }}</td>
                                </tr>
                                <tr>
                                    <th>Total Orders</th>
                                    <td>{{ $report->data['total_orders'] }}</td>
                                </tr>
                                <tr>
                                    <th>Total Amount</th>
                                    <td>${{ number_format($report->data['total_amount'], 2) }}</td>
                                </tr>
                                @elseif($report->report_type == 'department')
                                <tr>
                                    <th width="200">Total Departments</th>
                                    <td>{{ $report->data['total_departments'] }}</td>
                                </tr>
                                <tr>
                                    <th>Total Issues</th>
                                    <td>{{ $report->data['total_issues'] }}</td>
                                </tr>
                                <tr>
                                    <th>Total Items Issued</th>
                                    <td>{{ $report->data['total_items_issued'] }}</td>
                                </tr>
                                @endif
                            </table>
                        </div>
                    </div>

                    <h5>Report Details</h5>
                    @if($report->report_type == 'inventory')
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Type</th>
                                    <th>Quantity</th>
                                    <th>Price Per Item</th>
                                    <th>Min Stock Level</th>
                                    <th>Status</th>
                                    <th>Total Value</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if(isset($report->data['products']) && count($report->data['products']) > 0)
                                @foreach($report->data['products'] as $product)
                                <tr class="{{ $product['quantity'] <= $product['min_stock_level'] ? 'table-danger' : '' }}">
                                    <td>{{ $product['id'] }}</td>
                                    <td>{{ $product['name'] }}</td>
                                    <td>{{ $product['type'] }}</td>
                                    <td>{{ $product['quantity'] }}</td>
                                    <td>${{ number_format($product['price_per_item'], 2) }}</td>
                                    <td>{{ $product['min_stock_level'] }}</td>
                                    <td>{{ $product['status'] }}</td>
                                    <td>${{ number_format($product['total_value'], 2) }}</td>
                                </tr>
                                @endforeach
                                @else
                                <tr>
                                    <td colspan="8" class="text-center">No products found.</td>
                                </tr>
                                @endif
                            </tbody>
                        </table>
                    </div>
                    @elseif($report->report_type == 'purchase_order')
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Supplier</th>
                                    <th>Total Amount</th>
                                    <th>Status</th>
                                    <th>Date</th>
                                    <th>Items Count</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if(isset($report->data['purchase_orders']) && count($report->data['purchase_orders']) > 0)
                                @foreach($report->data['purchase_orders'] as $po)
                                <tr>
                                    <td>{{ $po['id'] }}</td>
                                    <td>{{ $po['supplier'] }}</td>
                                    <td>${{ number_format($po['total_amount'], 2) }}</td>
                                    <td>{{ $po['status'] }}</td>
                                    <td>{{ $po['created_at'] }}</td>
                                    <td>{{ $po['items_count'] }}</td>
                                </tr>
                                @endforeach
                                @else
                                <tr>
                                    <td colspan="6" class="text-center">No purchase orders found.</td>
                                </tr>
                                @endif
                            </tbody>
                        </table>
                    </div>
                    @elseif($report->report_type == 'issue')
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Product</th>
                                    <th>Employee</th>
                                    <th>Department</th>
                                    <th>Quantity Issued</th>
                                    <th>Issue Date</th>
                                    <th>Reason</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if(isset($report->data['issues']) && count($report->data['issues']) > 0)
                                @foreach($report->data['issues'] as $issue)
                                <tr>
                                    <td>{{ $issue['id'] }}</td>
                                    <td>{{ $issue['product'] }}</td>
                                    <td>{{ $issue['employee'] }}</td>
                                    <td>{{ $issue['department'] }}</td>
                                    <td>{{ $issue['quantity_issued'] }}</td>
                                    <td>{{ $issue['issue_date'] }}</td>
                                    <td>{{ $issue['reason'] }}</td>
                                </tr>
                                @endforeach
                                @else
                                <tr>
                                    <td colspan="7" class="text-center">No issues found.</td>
                                </tr>
                                @endif
                            </tbody>
                        </table>
                    </div>
                    @elseif($report->report_type == 'supplier')
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Contact Number</th>
                                    <th>Email</th>
                                    <th>Orders Count</th>
                                    <th>Total Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if(isset($report->data['suppliers']) && count($report->data['suppliers']) > 0)
                                @foreach($report->data['suppliers'] as $supplier)
                                <tr>
                                    <td>{{ $supplier['id'] }}</td>
                                    <td>{{ $supplier['name'] }}</td>
                                    <td>{{ $supplier['contact_number'] }}</td>
                                    <td>{{ $supplier['email'] }}</td>
                                    <td>{{ $supplier['orders_count'] }}</td>
                                    <td>${{ number_format($supplier['total_amount'], 2) }}</td>
                                </tr>
                                @endforeach
                                @else
                                <tr>
                                    <td colspan="6" class="text-center">No suppliers found.</td>
                                </tr>
                                @endif
                            </tbody>
                        </table>
                    </div>
                    @elseif($report->report_type == 'department')
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Issues Count</th>
                                    <th>Total Items</th>
                                    <th>Top Products</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if(isset($report->data['departments']) && count($report->data['departments']) > 0)
                                @foreach($report->data['departments'] as $dept)
                                <tr>
                                    <td>{{ $dept['id'] }}</td>
                                    <td>{{ $dept['name'] }}</td>
                                    <td>{{ $dept['issues_count'] }}</td>
                                    <td>{{ $dept['total_items'] }}</td>
                                    <td>
                                        @if(count($dept['top_products']) > 0)
                                        <ul class="mb-0">
                                            @foreach($dept['top_products'] as $product)
                                            <li>{{ $product['name'] }} ({{ $product['quantity'] }})</li>
                                            @endforeach
                                        </ul>
                                        @else
                                        No products
                                        @endif
                                    </td>
                                </tr>
                                @endforeach
                                @else
                                <tr>
                                    <td colspan="5" class="text-center">No departments found.</td>
                                </tr>
                                @endif
                            </tbody>
                        </table>
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection